# Source - https://stackoverflow.com/a/70452325
# Posted by frennky, modified by community. See post 'Timeline' for change history
# Retrieved 2026-05-19, License - CC BY-SA 4.0

name: Print environment variable

on:
 # push:
 #   branches:
 #     - main
 #     - development
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: Dev
        required: true
        type: choice
        options:
          - Test
          - Staging
          - Prod

jobs:    
  prod:
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' || github.event.inputs.environment == 'PROD' }}
    env:
      environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
        
  test:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' || github.event.inputs.environment == 'Test' }}
    env:
      environment: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print env value
        run: echo ${{ env.environment }}
